/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectatorIndexRouteImport } from './routes/spectator/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as CustomizeIndexRouteImport } from './routes/customize/index'
import { Route as SpectatorWatchRouteImport } from './routes/spectator/watch'
import { Route as GamePlayRouteImport } from './routes/game/play'
import { Route as GameDifficultyRouteImport } from './routes/game/difficulty'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorIndexRoute = SpectatorIndexRouteImport.update({
  id: '/spectator/',
  path: '/spectator/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeIndexRoute = CustomizeIndexRouteImport.update({
  id: '/customize/',
  path: '/customize/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorWatchRoute = SpectatorWatchRouteImport.update({
  id: '/spectator/watch',
  path: '/spectator/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: '/game/play',
  path: '/game/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDifficultyRoute = GameDifficultyRouteImport.update({
  id: '/game/difficulty',
  path: '/game/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/difficulty': typeof GameDifficultyRoute
  '/game/play': typeof GamePlayRoute
  '/spectator/watch': typeof SpectatorWatchRoute
  '/customize/': typeof CustomizeIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/spectator/': typeof SpectatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/difficulty': typeof GameDifficultyRoute
  '/game/play': typeof GamePlayRoute
  '/spectator/watch': typeof SpectatorWatchRoute
  '/customize': typeof CustomizeIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/spectator': typeof SpectatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/difficulty': typeof GameDifficultyRoute
  '/game/play': typeof GamePlayRoute
  '/spectator/watch': typeof SpectatorWatchRoute
  '/customize/': typeof CustomizeIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/spectator/': typeof SpectatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/difficulty'
    | '/game/play'
    | '/spectator/watch'
    | '/customize/'
    | '/rankings/'
    | '/shop/'
    | '/spectator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/difficulty'
    | '/game/play'
    | '/spectator/watch'
    | '/customize'
    | '/rankings'
    | '/shop'
    | '/spectator'
  id:
    | '__root__'
    | '/'
    | '/game/difficulty'
    | '/game/play'
    | '/spectator/watch'
    | '/customize/'
    | '/rankings/'
    | '/shop/'
    | '/spectator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameDifficultyRoute: typeof GameDifficultyRoute
  GamePlayRoute: typeof GamePlayRoute
  SpectatorWatchRoute: typeof SpectatorWatchRoute
  CustomizeIndexRoute: typeof CustomizeIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  SpectatorIndexRoute: typeof SpectatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/': {
      id: '/spectator/'
      path: '/spectator'
      fullPath: '/spectator/'
      preLoaderRoute: typeof SpectatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/': {
      id: '/customize/'
      path: '/customize'
      fullPath: '/customize/'
      preLoaderRoute: typeof CustomizeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/watch': {
      id: '/spectator/watch'
      path: '/spectator/watch'
      fullPath: '/spectator/watch'
      preLoaderRoute: typeof SpectatorWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play': {
      id: '/game/play'
      path: '/game/play'
      fullPath: '/game/play'
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/difficulty': {
      id: '/game/difficulty'
      path: '/game/difficulty'
      fullPath: '/game/difficulty'
      preLoaderRoute: typeof GameDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameDifficultyRoute: GameDifficultyRoute,
  GamePlayRoute: GamePlayRoute,
  SpectatorWatchRoute: SpectatorWatchRoute,
  CustomizeIndexRoute: CustomizeIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  SpectatorIndexRoute: SpectatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
